wandb_version: 1

chunk_size:
  desc: null
  value: 128
split_percentage:
  desc: null
  value: 0.8
batch_size:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.0001
ntokens:
  desc: null
  value: 256
d_model:
  desc: null
  value: 512
d_hid:
  desc: null
  value: 512
nlayers:
  desc: null
  value: 16
nhead:
  desc: null
  value: 6
dropout:
  desc: null
  value: 0.2
num_latent_vectors:
  desc: null
  value: 24000
use_bits:
  desc: null
  value: false
compression_factor:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711946938.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
